package tech.kayys.tafkir.ml;

import java.nio.file.Path;
import java.util.List;
import tech.kayys.tafkir.ml.Aljabr.DL.SchedulerFactory;
import tech.kayys.tafkir.ml.Aljabr.DL.TrainingOptions;
import tech.kayys.tafkir.ml.Aljabr.DL.TrainingPreset;
import tech.kayys.tafkir.ml.nn.NNModule;
import tech.kayys.tafkir.ml.optim.GradScaler;
import tech.kayys.tafkir.ml.train.CanonicalTrainer;
import tech.kayys.tafkir.train.data.DataLoader.Batch;

@SuppressWarnings("deprecation")
final class AljabrTrainingRequests {
    private AljabrTrainingRequests() {
    }

    static AljabrTrainingRuntime.Request fromOptions(
            NNModule model,
            Iterable<Batch> trainLoader,
            Iterable<Batch> validationLoader,
            int epochs,
            float learningRate,
            TrainingPreset preset,
            TrainingOptions options) {
        TrainingOptions resolvedOptions = options == null ? TrainingOptions.builder().build() : options;
        return fromResolvedValues(
                model,
                trainLoader,
                validationLoader,
                epochs,
                learningRate,
                preset,
                resolvedOptions.gradientClip(),
                resolvedOptions.gradientClipValue(),
                resolvedOptions.earlyStoppingPatience(),
                resolvedOptions.earlyStoppingMinDelta(),
                resolvedOptions.earlyStoppingMonitorMetric(),
                resolvedOptions.earlyStoppingMonitorMode(),
                resolvedOptions.checkpointDir(),
                resolvedOptions.resumeFromCheckpoint(),
                resolvedOptions.failOnCheckpointLoadError(),
                resolvedOptions.saveBestModelCheckpoint(),
                resolvedOptions.restoreBestModelAtEnd(),
                resolvedOptions.bestModelMonitorMetric(),
                resolvedOptions.bestModelMonitorMode(),
                resolvedOptions.gradientAccumulationSteps(),
                resolvedOptions.mixedPrecision(),
                resolvedOptions.gradScaler(),
                resolvedOptions.device(),
                resolvedOptions.failOnAcceleratorFallback(),
                resolvedOptions.dataDistributionDiagnostics(),
                resolvedOptions.metricFactories(),
                resolvedOptions.schedulerFactory(),
                resolvedOptions.schedulerStepUnit(),
                resolvedOptions.schedulerMonitorMetric(),
                resolvedOptions.crossEntropyClassWeights(),
                resolvedOptions.focalGamma(),
                resolvedOptions.focalAlpha(),
                resolvedOptions.focalClassWeights(),
                resolvedOptions.causalLanguageModelingIgnoreIndex(),
                resolvedOptions.bcePositiveWeights(),
                resolvedOptions.pinballQuantiles(),
                resolvedOptions.intervalAlpha(),
                resolvedOptions.intervalCrossingPenalty(),
                resolvedOptions.tweediePower(),
                resolvedOptions.tweedieLogInput(),
                resolvedOptions.tweedieEps(),
                resolvedOptions.negativeBinomialLogInput(),
                resolvedOptions.negativeBinomialIncludeConstant(),
                resolvedOptions.negativeBinomialEps(),
                resolvedOptions.zeroInflatedPoissonLogRateInput(),
                resolvedOptions.zeroInflatedPoissonIncludeConstant(),
                resolvedOptions.zeroInflatedPoissonEps(),
                resolvedOptions.zeroInflatedNegativeBinomialLogInput(),
                resolvedOptions.zeroInflatedNegativeBinomialIncludeConstant(),
                resolvedOptions.zeroInflatedNegativeBinomialEps());
    }

    static AljabrTrainingRuntime.Request fromLegacy(
            NNModule model,
            Iterable<Batch> trainLoader,
            Iterable<Batch> validationLoader,
            int epochs,
            float learningRate,
            TrainingPreset preset,
            double gradientClip,
            int earlyStoppingPatience,
            double earlyStoppingMinDelta,
            Path checkpointDir,
            boolean resumeFromCheckpoint,
            boolean failOnCheckpointLoadError,
            int gradientAccumulationSteps,
            String deviceId) {
        return fromResolvedValues(
                model,
                trainLoader,
                validationLoader,
                epochs,
                learningRate,
                preset,
                gradientClip,
                0.0,
                earlyStoppingPatience,
                earlyStoppingMinDelta,
                null,
                CanonicalTrainer.BestModelMonitorMode.MIN,
                checkpointDir,
                resumeFromCheckpoint,
                failOnCheckpointLoadError,
                true,
                false,
                null,
                CanonicalTrainer.BestModelMonitorMode.MIN,
                gradientAccumulationSteps,
                false,
                null,
                deviceId,
                false,
                false,
                List.of(),
                null,
                CanonicalTrainer.SchedulerStepUnit.BATCH,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }

    private static AljabrTrainingRuntime.Request fromResolvedValues(
            NNModule model,
            Iterable<Batch> trainLoader,
            Iterable<Batch> validationLoader,
            int epochs,
            float learningRate,
            TrainingPreset preset,
            double gradientClip,
            double gradientClipValue,
            int earlyStoppingPatience,
            double earlyStoppingMinDelta,
            String earlyStoppingMonitorMetric,
            CanonicalTrainer.BestModelMonitorMode earlyStoppingMonitorMode,
            Path checkpointDir,
            boolean resumeFromCheckpoint,
            boolean failOnCheckpointLoadError,
            boolean saveBestModelCheckpoint,
            boolean restoreBestModelAtEnd,
            String bestModelMonitorMetric,
            CanonicalTrainer.BestModelMonitorMode bestModelMonitorMode,
            int gradientAccumulationSteps,
            boolean mixedPrecision,
            GradScaler gradScaler,
            String deviceId,
            boolean failOnAcceleratorFallback,
            boolean dataDistributionDiagnostics,
            List<java.util.function.Supplier<? extends CanonicalTrainer.Metric>> metricFactories,
            SchedulerFactory schedulerFactory,
            CanonicalTrainer.SchedulerStepUnit schedulerStepUnit,
            String schedulerMonitorMetric,
            float[] crossEntropyClassWeights,
            Float focalGamma,
            Float focalAlpha,
            float[] focalClassWeights,
            Float causalLanguageModelingIgnoreIndex,
            float[] bcePositiveWeights,
            float[] pinballQuantiles,
            Float intervalAlpha,
            Float intervalCrossingPenalty,
            Float tweediePower,
            Boolean tweedieLogInput,
            Float tweedieEps,
            Boolean negativeBinomialLogInput,
            Boolean negativeBinomialIncludeConstant,
            Float negativeBinomialEps,
            Boolean zeroInflatedPoissonLogRateInput,
            Boolean zeroInflatedPoissonIncludeConstant,
            Float zeroInflatedPoissonEps,
            Boolean zeroInflatedNegativeBinomialLogInput,
            Boolean zeroInflatedNegativeBinomialIncludeConstant,
            Float zeroInflatedNegativeBinomialEps) {
        return new AljabrTrainingRuntime.Request(
                model,
                trainLoader,
                validationLoader,
                epochs,
                learningRate,
                preset,
                gradientClip,
                gradientClipValue,
                earlyStoppingPatience,
                earlyStoppingMinDelta,
                earlyStoppingMonitorMetric,
                earlyStoppingMonitorMode,
                checkpointDir,
                resumeFromCheckpoint,
                failOnCheckpointLoadError,
                saveBestModelCheckpoint,
                restoreBestModelAtEnd,
                bestModelMonitorMetric,
                bestModelMonitorMode,
                gradientAccumulationSteps,
                mixedPrecision,
                gradScaler,
                deviceId,
                failOnAcceleratorFallback,
                dataDistributionDiagnostics,
                metricFactories,
                schedulerFactory,
                schedulerStepUnit,
                schedulerMonitorMetric,
                crossEntropyClassWeights,
                focalGamma,
                focalAlpha,
                focalClassWeights,
                causalLanguageModelingIgnoreIndex,
                bcePositiveWeights,
                pinballQuantiles,
                intervalAlpha,
                intervalCrossingPenalty,
                tweediePower,
                tweedieLogInput,
                tweedieEps,
                negativeBinomialLogInput,
                negativeBinomialIncludeConstant,
                negativeBinomialEps,
                zeroInflatedPoissonLogRateInput,
                zeroInflatedPoissonIncludeConstant,
                zeroInflatedPoissonEps,
                zeroInflatedNegativeBinomialLogInput,
                zeroInflatedNegativeBinomialIncludeConstant,
                zeroInflatedNegativeBinomialEps);
    }
}
