#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu May 21 12:44:42 WIB 2026
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1779341863591
maven-metadata-github.xml.lastUpdated=1779326793901
maven-metadata-jboss-public-repository-group.xml.error=
maven-metadata-jboss-public-repository-group.xml.lastUpdated=1779326839723
maven-metadata-local-repository.xml.error=
maven-metadata-local-repository.xml.lastUpdated=1779326839722
maven-metadata-local.xml.error=Could not transfer metadata tech.kayys.tafkir\:tafkir-model-runner\:0.1.0-SNAPSHOT/maven-metadata.xml from/to local (local)\: Cannot access local with type default using the available connector factories\: BasicRepositoryConnectorFactory
maven-metadata-local.xml/@default-local-local/.lastUpdated=1779342005011
maven-metadata-mavencentral.xml.error=
maven-metadata-mavencentral.xml.lastUpdated=1779342088437
maven-metadata-mavenlocal.xml.error=Could not transfer metadata tech.kayys.tafkir\:tafkir-model-runner\:0.1.0-SNAPSHOT/maven-metadata.xml from/to mavenlocal (mavenLocal)\: Cannot access mavenLocal with type default using the available connector factories\: BasicRepositoryConnectorFactory
maven-metadata-mavenlocal.xml/@default-mavenlocal-mavenLocal/.lastUpdated=1779342282597
maven-metadata-ossrh.xml.error=
maven-metadata-ossrh.xml.lastUpdated=1779326839723
