#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Dec 22 07:08:10 WIB 2025
maven-metadata-central.xml.lastUpdated=1766362090435
maven-metadata-jboss-public-repository-group.xml.error=
maven-metadata-jboss-public-repository-group.xml.lastUpdated=1766362090435
maven-metadata-local-repository.xml.error=
maven-metadata-local-repository.xml.lastUpdated=1766362090435
