package tech.kayys.tafkir.jupyter;

final class NotebookStartupScripts {

    private static final String DEFAULT_STARTUP_SCRIPT = String.join("\n",
            "import java.awt.Color;",
            "import java.awt.image.BufferedImage;",
            "import java.io.ByteArrayOutputStream;",
            "import java.util.ArrayList;",
            "import java.util.LinkedHashMap;",
            "import java.util.List;",
            "import java.util.Map;",
            "import java.nio.ByteBuffer;",
            "import java.nio.ByteOrder;",
            "import tech.kayys.tafkir.jupyter.NotebookAudioClip;",
            "import tech.kayys.tafkir.jupyter.NotebookLineChart;",
            "import tech.kayys.tafkir.ml.autograd.GradTensor;",
            "import tech.kayys.tafkir.ml.nn.layer.Linear;",
            "import tech.kayys.tafkir.ml.nn.layer.ReLU;",
            "import tech.kayys.tafkir.ml.nn.layer.Sequential;",
            "",
            "String tafkirHelp() {",
            "    return String.join(\"\\n\",",
            "        \"Tafkir notebook helpers:\",",
            "        \"  - GradTensor.ones(2, 2)\",",
            "        \"  - new Sequential(new Linear(2, 3), new ReLU())\",",
            "        \"  - tafkirTensorDemo()\",",
            "        \"  - tafkirMetricsDemo()\",",
            "        \"  - tafkirLossCurveDemo()\",",
            "        \"  - tafkirImageDemo()\",",
            "        \"  - tafkirAudioDemo()\",",
            "        \"  - tafkirModelSummary()\",",
            "        \"  - tafkirModelDemo()\"",
            "    );",
            "}",
            "",
            "GradTensor tafkirTensorDemo() {",
            "    return GradTensor.ones(2, 2);",
            "}",
            "",
            "GradTensor tafkirPreviewTensorDemo() {",
            "    return GradTensor.of(new float[]{0f, 1f, 2f, 3f}, 2, 2);",
            "}",
            "",
            "List<Map<String, Object>> tafkirMetricsDemo() {",
            "    var rows = new ArrayList<Map<String, Object>>();",
            "    var row1 = new LinkedHashMap<String, Object>();",
            "    row1.put(\"epoch\", 1);",
            "    row1.put(\"loss\", 0.91);",
            "    row1.put(\"accuracy\", 0.72);",
            "    rows.add(row1);",
            "    var row2 = new LinkedHashMap<String, Object>();",
            "    row2.put(\"epoch\", 2);",
            "    row2.put(\"loss\", 0.42);",
            "    row2.put(\"accuracy\", 0.88);",
            "    rows.add(row2);",
            "    return rows;",
            "}",
            "",
            "NotebookLineChart tafkirLossCurveDemo() {",
            "    return NotebookLineChart.of(\"Training Loss\", \"epoch\", \"loss\", 0.91, 0.68, 0.52, 0.42, 0.31);",
            "}",
            "",
            "BufferedImage tafkirImageDemo() {",
            "    var image = new BufferedImage(4, 4, BufferedImage.TYPE_INT_RGB);",
            "    for (int y = 0; y < 4; y++) {",
            "        for (int x = 0; x < 4; x++) {",
            "            image.setRGB(x, y, ((x + y) % 2 == 0 ? Color.ORANGE : Color.BLUE).getRGB());",
            "        }",
            "    }",
            "    return image;",
            "}",
            "",
            "NotebookAudioClip tafkirAudioDemo() {",
            "    int sampleRate = 8000;",
            "    double seconds = 0.25;",
            "    int sampleCount = (int) (sampleRate * seconds);",
            "    byte[] pcm = new byte[sampleCount * 2];",
            "    for (int i = 0; i < sampleCount; i++) {",
            "        double sample = Math.sin(2.0 * Math.PI * 440.0 * i / sampleRate);",
            "        short value = (short) (sample * 12000);",
            "        pcm[i * 2] = (byte) (value & 0xff);",
            "        pcm[i * 2 + 1] = (byte) ((value >>> 8) & 0xff);",
            "    }",
            "    return NotebookAudioClip.ofWav(\"Demo Tone\", sampleRate, 1, tafkirWrapWav(pcm, sampleRate, 1, 16));",
            "}",
            "",
            "byte[] tafkirWrapWav(byte[] pcm, int sampleRate, int channels, int bitsPerSample) {",
            "    int byteRate = sampleRate * channels * bitsPerSample / 8;",
            "    int blockAlign = channels * bitsPerSample / 8;",
            "    ByteBuffer buffer = ByteBuffer.allocate(44 + pcm.length).order(ByteOrder.LITTLE_ENDIAN);",
            "    buffer.put(new byte[]{'R','I','F','F'});",
            "    buffer.putInt(36 + pcm.length);",
            "    buffer.put(new byte[]{'W','A','V','E'});",
            "    buffer.put(new byte[]{'f','m','t',' '});",
            "    buffer.putInt(16);",
            "    buffer.putShort((short) 1);",
            "    buffer.putShort((short) channels);",
            "    buffer.putInt(sampleRate);",
            "    buffer.putInt(byteRate);",
            "    buffer.putShort((short) blockAlign);",
            "    buffer.putShort((short) bitsPerSample);",
            "    buffer.put(new byte[]{'d','a','t','a'});",
            "    buffer.putInt(pcm.length);",
            "    buffer.put(pcm);",
            "    return buffer.array();",
            "}",
            "",
            "Sequential tafkirModelDemo() {",
            "    return new Sequential(new Linear(2, 3), new ReLU());",
            "}",
            "",
            "String tafkirModelSummary() {",
            "    var model = tafkirModelDemo();",
            "    return \"Sequential(layers=\" + model.size() + \", parameters=\" + model.parameterCount() + \")\";",
            "}"
    );

    private NotebookStartupScripts() {
    }

    static String defaultScript() {
        return DEFAULT_STARTUP_SCRIPT;
    }
}
