package tech.kayys.tafkir.ml.train;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;

class TrainerCheckpointResumeIssueMetadataTest {

    @Test
    void snapshotBuildsStructuredIssueDiagnostics() {
        TrainerCheckpointResumeIssueMetadata.Snapshot snapshot =
                TrainerCheckpointResumeIssueMetadata.snapshot(
                        List.of("optimizer"),
                        List.of("model: signature mismatch"),
                        List.of("runtime"));

        assertTrue(snapshot.issueDetected());
        assertEquals(3, snapshot.issueCount());
        assertEquals(
                List.of("missing-artifact", "compatibility-mismatch", "manifest-entry-missing"),
                snapshot.issueKinds());
        assertEquals(List.of("optimizer", "model", "runtime"), snapshot.affectedArtifacts());
        assertEquals(
                List.of(
                        "checkpoint-resume-artifact-missing",
                        "checkpoint-resume-compatibility-mismatch",
                        "checkpoint-resume-manifest-entry-missing"),
                snapshot.issueCodes());
        assertEquals(List.of("warning", "error"), snapshot.issueSeverities());
        assertTrue(snapshot.blockingIssueDetected());
        assertEquals(1, snapshot.blockingIssueCount());
        assertEquals(List.of("compatibility-mismatch"), snapshot.blockingIssueKinds());
        assertEquals(
                List.of(issue(
                        "compatibility-mismatch",
                        "checkpoint-resume-compatibility-mismatch",
                        "error",
                        true,
                        "model",
                        "signature mismatch",
                        "use a checkpoint generated by the same trainer configuration or start a fresh run")),
                snapshot.blockingIssues());
        assertEquals(
                List.of(
                        "restore the missing artifact or resume without checkpoint state",
                        "use a checkpoint generated by the same trainer configuration or start a fresh run",
                        "restore a complete checkpoint manifest or regenerate the checkpoint set"),
                snapshot.recommendedActions());
        assertTrue(snapshot.primaryIssueAvailable());
        assertEquals("missing-artifact", snapshot.primaryIssueKind());
        assertEquals("checkpoint-resume-artifact-missing", snapshot.primaryIssueCode());
        assertEquals("warning", snapshot.primaryIssueSeverity());
        assertEquals(false, snapshot.primaryIssueBlocking());
        assertTrue(snapshot.primaryBlockingIssueAvailable());
        assertEquals("compatibility-mismatch", snapshot.primaryBlockingIssueKind());
        assertEquals("checkpoint-resume-compatibility-mismatch", snapshot.primaryBlockingIssueCode());
        assertEquals("error", snapshot.primaryBlockingIssueSeverity());
        assertEquals("model", snapshot.primaryBlockingAffectedArtifact());
        assertEquals("signature mismatch", snapshot.primaryBlockingIssueMessage());
        assertEquals(
                "use a checkpoint generated by the same trainer configuration or start a fresh run",
                snapshot.primaryBlockingRecommendedAction());
        assertEquals("optimizer", snapshot.primaryAffectedArtifact());
        assertEquals("optimizer checkpoint artifact is missing on resume", snapshot.primaryIssueMessage());
        assertEquals(
                "restore the missing artifact or resume without checkpoint state",
                snapshot.primaryRecommendedAction());
        assertEquals(
                Map.of(
                        "missing-artifact", 1,
                        "compatibility-mismatch", 1,
                        "manifest-entry-missing", 1),
                snapshot.issueCountsByKind());
        assertEquals(
                Map.of(
                        "missing-artifact", "warning",
                        "compatibility-mismatch", "error",
                        "manifest-entry-missing", "warning"),
                snapshot.issueSeveritiesByKind());
        assertEquals(
                Map.of(
                        "missing-artifact", false,
                        "compatibility-mismatch", true,
                        "manifest-entry-missing", false),
                snapshot.issueBlockingByKind());
        assertEquals(
                Map.of(
                        "missing-artifact", List.of("optimizer"),
                        "compatibility-mismatch", List.of("model"),
                        "manifest-entry-missing", List.of("runtime")),
                snapshot.issueArtifactsByKind());
        assertEquals(
                List.of(
                        issue(
                                "missing-artifact",
                                "checkpoint-resume-artifact-missing",
                                "warning",
                                false,
                                "optimizer",
                                "optimizer checkpoint artifact is missing on resume",
                                "restore the missing artifact or resume without checkpoint state"),
                        issue(
                                "compatibility-mismatch",
                                "checkpoint-resume-compatibility-mismatch",
                                "error",
                                true,
                                "model",
                                "signature mismatch",
                                "use a checkpoint generated by the same trainer configuration or start a fresh run"),
                        issue(
                                "manifest-entry-missing",
                                "checkpoint-resume-manifest-entry-missing",
                                "warning",
                                false,
                                "runtime",
                                "runtime checkpoint is missing from checkpoint manifest",
                                "restore a complete checkpoint manifest or regenerate the checkpoint set")),
                snapshot.issues());
    }

    @Test
    void snapshotTreatsNullInputsAsEmpty() {
        TrainerCheckpointResumeIssueMetadata.Snapshot snapshot =
                TrainerCheckpointResumeIssueMetadata.snapshot(null, null, null);

        assertFalse(snapshot.issueDetected());
        assertFalse(snapshot.hasCompatibilityMismatches());
        assertFalse(snapshot.hasManifestEntryMissingArtifacts());
        assertEquals(0, snapshot.issueCount());
        assertEquals(List.of(), snapshot.missingArtifacts());
        assertEquals(List.of(), snapshot.compatibilityMismatches());
        assertEquals(List.of(), snapshot.manifestEntryMissingArtifacts());
        assertEquals(List.of(), snapshot.issueKinds());
        assertEquals(List.of(), snapshot.affectedArtifacts());
        assertEquals(List.of(), snapshot.issues());
        assertEquals(List.of(), snapshot.issueCodes());
        assertEquals(List.of(), snapshot.issueSeverities());
        assertFalse(snapshot.blockingIssueDetected());
        assertEquals(0, snapshot.blockingIssueCount());
        assertEquals(List.of(), snapshot.blockingIssueKinds());
        assertEquals(List.of(), snapshot.blockingIssues());
        assertEquals(List.of(), snapshot.recommendedActions());
        assertFalse(snapshot.primaryIssueAvailable());
        assertEquals(null, snapshot.primaryIssueKind());
        assertEquals(null, snapshot.primaryIssueCode());
        assertEquals(null, snapshot.primaryIssueSeverity());
        assertEquals(false, snapshot.primaryIssueBlocking());
        assertFalse(snapshot.primaryBlockingIssueAvailable());
        assertEquals(null, snapshot.primaryBlockingIssueKind());
        assertEquals(null, snapshot.primaryBlockingIssueCode());
        assertEquals(null, snapshot.primaryBlockingIssueSeverity());
        assertEquals(null, snapshot.primaryBlockingAffectedArtifact());
        assertEquals(null, snapshot.primaryBlockingIssueMessage());
        assertEquals(null, snapshot.primaryBlockingRecommendedAction());
        assertEquals(null, snapshot.primaryAffectedArtifact());
        assertEquals(null, snapshot.primaryIssueMessage());
        assertEquals(null, snapshot.primaryRecommendedAction());
        assertEquals(Map.of(), snapshot.issueCountsByKind());
        assertEquals(Map.of(), snapshot.issueSeveritiesByKind());
        assertEquals(Map.of(), snapshot.issueBlockingByKind());
        assertEquals(Map.of(), snapshot.issueArtifactsByKind());
    }

    @Test
    void snapshotNormalizesAffectedArtifactNames() {
        TrainerCheckpointResumeIssueMetadata.Snapshot snapshot =
                TrainerCheckpointResumeIssueMetadata.snapshot(
                        List.of("optimizer", " optimizer "),
                        List.of(" model : signature mismatch"),
                        List.of("runtime", " runtime "));

        assertEquals(List.of("optimizer", "model", "runtime"), snapshot.affectedArtifacts());
        assertEquals(
                Map.of(
                        "missing-artifact", List.of("optimizer"),
                        "compatibility-mismatch", List.of("model"),
                        "manifest-entry-missing", List.of("runtime")),
                snapshot.issueArtifactsByKind());
    }

    @Test
    void snapshotDeduplicatesTopLevelCodesAndActionsByIssueKind() {
        TrainerCheckpointResumeIssueMetadata.Snapshot snapshot =
                TrainerCheckpointResumeIssueMetadata.snapshot(
                        List.of("optimizer", "scheduler"),
                        List.of(),
                        List.of());

        assertEquals(2, snapshot.issueCount());
        assertEquals(
                List.of("checkpoint-resume-artifact-missing"),
                snapshot.issueCodes());
        assertEquals(List.of("warning"), snapshot.issueSeverities());
        assertFalse(snapshot.blockingIssueDetected());
        assertEquals(0, snapshot.blockingIssueCount());
        assertEquals(List.of(), snapshot.blockingIssueKinds());
        assertEquals(List.of(), snapshot.blockingIssues());
        assertFalse(snapshot.primaryBlockingIssueAvailable());
        assertEquals(
                List.of("restore the missing artifact or resume without checkpoint state"),
                snapshot.recommendedActions());
        assertEquals("optimizer", snapshot.primaryAffectedArtifact());
    }

    @Test
    void snapshotStoresImmutableCopies() {
        List<String> missing = new ArrayList<>(List.of("optimizer"));
        List<String> mismatches = new ArrayList<>(List.of("scheduler"));
        List<String> missingManifestEntries = new ArrayList<>(List.of("gradScaler"));

        TrainerCheckpointResumeIssueMetadata.Snapshot snapshot =
                TrainerCheckpointResumeIssueMetadata.snapshot(missing, mismatches, missingManifestEntries);
        missing.add("late-missing");
        mismatches.add("late-mismatch");
        missingManifestEntries.add("late-manifest-entry");

        assertEquals(List.of("optimizer"), snapshot.missingArtifacts());
        assertEquals(List.of("scheduler"), snapshot.compatibilityMismatches());
        assertEquals(List.of("gradScaler"), snapshot.manifestEntryMissingArtifacts());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.missingArtifacts().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.issueKinds().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.affectedArtifacts().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.issues().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.issues().getFirst().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.blockingIssues().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.blockingIssues().getFirst().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.issueCodes().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.issueSeverities().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.recommendedActions().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.issueCountsByKind().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.issueSeveritiesByKind().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.issueBlockingByKind().clear());
        assertThrows(UnsupportedOperationException.class, () -> snapshot.issueArtifactsByKind().clear());
        assertThrows(
                UnsupportedOperationException.class,
                () -> snapshot.issueArtifactsByKind().get("missing-artifact").clear());
    }

    private static Map<String, Object> issue(
            String kind,
            String code,
            String severity,
            boolean blocking,
            String artifact,
            String message,
            String action) {
        return Map.of(
                "kind", kind,
                "code", code,
                "severity", severity,
                "blocking", blocking,
                "artifact", artifact,
                "message", message,
                "action", action);
    }
}
