package tech.kayys.tafkir.ml.train;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;

class TrainerRunHealthMetadataTest {

    @Test
    void publishesHealthyStatusWhenNoRunIssuesArePresent() {
        Map<String, Object> metadata = new HashMap<>();

        TrainerRunHealthMetadata.put(metadata);

        assertEquals("healthy", metadata.get("trainingRunHealthStatus"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunHealthy"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunIssueDetected"));
        assertEquals(0, metadata.get("trainingRunIssueCount"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunBlockingIssueDetected"));
        assertEquals(0, metadata.get("trainingRunBlockingIssueCount"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunGatePassed"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunPrimaryIssueAvailable"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunPrimaryBlockingIssueAvailable"));
        assertEquals("continue monitoring training", metadata.get("trainingRunRecommendedAction"));
        assertEquals(List.of(), metadata.get("trainingRunIssueCodes"));
        assertEquals(List.of(), metadata.get("trainingRunIssues"));
        assertThrows(UnsupportedOperationException.class, () -> trainingRunIssues(metadata).clear());
    }

    @Test
    void publishesStructuredRunHealthIssuesFromExistingDiagnostics() {
        Map<String, Object> metadata = new HashMap<>();
        metadata.put("nonFiniteDetected", true);
        metadata.put("nonFiniteMessage", "train gradient must be finite, got NaN");
        metadata.put("checkpointResumeBlockingIssueDetected", true);
        metadata.put("checkpointResumePrimaryBlockingIssueCode", "checkpoint-resume-compatibility-mismatch");
        metadata.put("checkpointResumePrimaryBlockingAffectedArtifact", "optimizer");
        metadata.put("checkpointResumePrimaryBlockingIssueMessage", "parameter signature mismatch");
        metadata.put(
                "checkpointResumePrimaryBlockingRecommendedAction",
                "use a checkpoint generated by the same trainer configuration or start a fresh run");
        metadata.put("runtimeCheckpointIntegrityMismatch", true);
        metadata.put("runtimeCheckpointResumeDecision", "runtime-checkpoint-integrity-mismatch");
        metadata.put(
                "runtimeCheckpointRecommendedAction",
                "skip runtime checkpoint and rebuild runtime state from trainer artifacts");
        metadata.put("executionFallback", true);
        metadata.put("requestedDevice", "metal");
        metadata.put("executionBackend", "cpu");
        metadata.put("mixedPrecisionOverflowDetected", true);

        TrainerRunHealthMetadata.put(metadata);

        assertEquals("failed", metadata.get("trainingRunHealthStatus"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunHealthy"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunIssueDetected"));
        assertEquals(5, metadata.get("trainingRunIssueCount"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunBlockingIssueDetected"));
        assertEquals(2, metadata.get("trainingRunBlockingIssueCount"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunGatePassed"));
        assertEquals(
                List.of(
                        "non-finite-detected",
                        "checkpoint-resume-compatibility-mismatch",
                        "runtime-checkpoint-integrity-mismatch",
                        "accelerator-fallback",
                        "mixed-precision-overflow"),
                metadata.get("trainingRunIssueCodes"));
        assertEquals(List.of("error", "warning"), metadata.get("trainingRunIssueSeverities"));
        assertEquals(
                Map.of(
                        "training-failure", 1,
                        "checkpoint-resume", 1,
                        "runtime-checkpoint", 1,
                        "accelerator", 1,
                        "mixed-precision", 1),
                metadata.get("trainingRunIssueCountsByKind"));
        assertEquals(Map.of("error", 2, "warning", 3), metadata.get("trainingRunIssueCountsBySeverity"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunPrimaryIssueAvailable"));
        assertEquals("non-finite-detected", metadata.get("trainingRunPrimaryIssueCode"));
        assertEquals("trainer", metadata.get("trainingRunPrimaryIssueArtifact"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunPrimaryBlockingIssueAvailable"));
        assertEquals("non-finite-detected", metadata.get("trainingRunPrimaryBlockingIssueCode"));
        assertEquals(
                "inspect data and loss scale, reduce learning rate, or enable gradient clipping",
                metadata.get("trainingRunRecommendedAction"));
        assertEquals(
                "inspect data and loss scale, reduce learning rate, or enable gradient clipping",
                trainingRunIssues(metadata).get(0).get("action"));
        assertEquals("optimizer", trainingRunIssues(metadata).get(1).get("artifact"));
        assertEquals("runtime", trainingRunIssues(metadata).get(2).get("artifact"));
        assertEquals("requested device 'metal' fell back to 'cpu'", trainingRunIssues(metadata).get(3).get("message"));
        assertThrows(UnsupportedOperationException.class, () -> trainingRunIssues(metadata).get(0).clear());
    }

    @Test
    void warningOnlyRunKeepsGatePassingWithPrimaryAction() {
        Map<String, Object> metadata = new HashMap<>();
        metadata.put("executionFallback", true);
        metadata.put("requestedDevice", "metal");
        metadata.put("executionBackend", "cpu");

        TrainerRunHealthMetadata.put(metadata);

        assertEquals("warning", metadata.get("trainingRunHealthStatus"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunHealthy"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunIssueDetected"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunBlockingIssueDetected"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunGatePassed"));
        assertEquals("accelerator-fallback", metadata.get("trainingRunPrimaryIssueCode"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunPrimaryBlockingIssueAvailable"));
        assertEquals(
                "install or enable the requested accelerator, or set device to the observed backend",
                metadata.get("trainingRunRecommendedAction"));
    }

    @Test
    void promotesDataLoaderPlanHealthIssuesIntoRunHealth() {
        Map<String, Object> metadata = new HashMap<>();
        metadata.put(
                "dataLoaderPlanHealthIssues",
                List.of(
                        Map.of(
                                "kind", "data-loader",
                                "code", "data-loader-train-plan-unavailable",
                                "severity", "error",
                                "blocking", Boolean.TRUE,
                                "artifact", "train",
                                "message", "train loader plan is unavailable",
                                "action", "use a DataLoader.TensorDataLoader for training"),
                        Map.of(
                                "kind", "data-loader",
                                "code", "data-loader-train-low-sampler-coverage",
                                "severity", "warning",
                                "blocking", Boolean.FALSE,
                                "artifact", "train",
                                "message", "train loader samples only 80.0% of the dataset per epoch",
                                "action", "increase sampler sample count")));

        TrainerRunHealthMetadata.put(metadata);

        assertEquals("failed", metadata.get("trainingRunHealthStatus"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunIssueDetected"));
        assertEquals(2, metadata.get("trainingRunIssueCount"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunBlockingIssueDetected"));
        assertEquals(1, metadata.get("trainingRunBlockingIssueCount"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunGatePassed"));
        assertEquals(
                List.of("data-loader-train-plan-unavailable", "data-loader-train-low-sampler-coverage"),
                metadata.get("trainingRunIssueCodes"));
        assertEquals(Map.of("data-loader", 2), metadata.get("trainingRunIssueCountsByKind"));
        assertEquals(Map.of("error", 1, "warning", 1), metadata.get("trainingRunIssueCountsBySeverity"));
        assertEquals("data-loader-train-plan-unavailable", metadata.get("trainingRunPrimaryIssueCode"));
        assertEquals("data-loader-train-plan-unavailable", metadata.get("trainingRunPrimaryBlockingIssueCode"));
        assertEquals("use a DataLoader.TensorDataLoader for training", metadata.get("trainingRunRecommendedAction"));
    }

    @Test
    void promotesDataDistributionHealthIssuesIntoRunHealthWarnings() {
        Map<String, Object> metadata = new HashMap<>();
        metadata.put(
                "dataDistributionHealthIssues",
                List.of(Map.of(
                        "kind", "data-distribution",
                        "code", "data-distribution-classification-drift",
                        "severity", "warning",
                        "blocking", Boolean.FALSE,
                        "artifact", "drift",
                        "message", "train/validation class distribution drift is high",
                        "action", "use stratified splitting")));

        TrainerRunHealthMetadata.put(metadata);

        assertEquals("warning", metadata.get("trainingRunHealthStatus"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunIssueDetected"));
        assertEquals(1, metadata.get("trainingRunIssueCount"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunBlockingIssueDetected"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunGatePassed"));
        assertEquals(List.of("data-distribution-classification-drift"), metadata.get("trainingRunIssueCodes"));
        assertEquals(Map.of("data-distribution", 1), metadata.get("trainingRunIssueCountsByKind"));
        assertEquals("use stratified splitting", metadata.get("trainingRunRecommendedAction"));
    }

    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> trainingRunIssues(Map<String, Object> metadata) {
        return (List<Map<String, Object>>) metadata.get("trainingRunIssues");
    }
}
