package tech.kayys.tafkir.ml.train;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import tech.kayys.tafkir.ml.autograd.Acceleration;
import tech.kayys.tafkir.trainer.api.TrainingSummary;

class TrainerSummaryAssemblerTest {

    @TempDir
    Path tempDir;

    @Test
    void enrichPublishesTrainerSummarySnapshotAcrossRuntimeDomains() throws Exception {
        TrainingSummary base = new TrainingSummary(
                3,
                0.12,
                2,
                0.34,
                0.23,
                987L,
                Map.of("seed", 42));
        TrainerFailureState failureState = new TrainerFailureState();

        TrainingSummary summary = TrainerSummaryAssembler.enrich(base, request(tempDir, failureState));

        Map<String, Object> metadata = summary.metadata();
        double trainWindowMean = (0.62 + 0.5 + 0.34) / 3.0;
        double trainWindowStdDev = Math.sqrt((
                Math.pow(0.62 - trainWindowMean, 2)
                        + Math.pow(0.5 - trainWindowMean, 2)
                        + Math.pow(0.34 - trainWindowMean, 2))
                / 3.0);
        double validationWindowMean = (0.51 + 0.4 + 0.23) / 3.0;
        double validationWindowStdDev = Math.sqrt((
                Math.pow(0.51 - validationWindowMean, 2)
                        + Math.pow(0.4 - validationWindowMean, 2)
                        + Math.pow(0.23 - validationWindowMean, 2))
                / 3.0);
        assertEquals(3, summary.epochCount());
        assertEquals(42, metadata.get("seed"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumePartial"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeStateUsable"));
        assertEquals("fresh-start", metadata.get("checkpointResumeRecommendedMode"));
        assertEquals(
                "start a fresh run or choose a compatible checkpoint before resuming",
                metadata.get("checkpointResumeNextAction"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeIssueDetected"));
        assertEquals(3, metadata.get("checkpointResumeIssueCount"));
        assertEquals(
                List.of("missing-artifact", "compatibility-mismatch", "manifest-entry-missing"),
                metadata.get("checkpointResumeIssueKinds"));
        assertEquals(
                List.of("scheduler", "optimizer", "runtime"),
                metadata.get("checkpointResumeAffectedArtifacts"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeBlockingIssueDetected"));
        assertEquals(1, metadata.get("checkpointResumeBlockingIssueCount"));
        assertEquals(List.of("compatibility-mismatch"), metadata.get("checkpointResumeBlockingIssueKinds"));
        assertEquals(
                List.of(issue(
                        "compatibility-mismatch",
                        "checkpoint-resume-compatibility-mismatch",
                        "error",
                        true,
                        "optimizer",
                        "parameter signature mismatch",
                        "use a checkpoint generated by the same trainer configuration or start a fresh run")),
                metadata.get("checkpointResumeBlockingIssues"));
        assertEquals(
                List.of(
                        "checkpoint-resume-artifact-missing",
                        "checkpoint-resume-compatibility-mismatch",
                        "checkpoint-resume-manifest-entry-missing"),
                metadata.get("checkpointResumeIssueCodes"));
        assertEquals(List.of("warning", "error"), metadata.get("checkpointResumeIssueSeverities"));
        assertEquals(
                List.of(
                        "restore the missing artifact or resume without checkpoint state",
                        "use a checkpoint generated by the same trainer configuration or start a fresh run",
                        "restore a complete checkpoint manifest or regenerate the checkpoint set"),
                metadata.get("checkpointResumeRecommendedActions"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumePrimaryIssueAvailable"));
        assertEquals("missing-artifact", metadata.get("checkpointResumePrimaryIssueKind"));
        assertEquals("checkpoint-resume-artifact-missing", metadata.get("checkpointResumePrimaryIssueCode"));
        assertEquals("warning", metadata.get("checkpointResumePrimaryIssueSeverity"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumePrimaryIssueBlocking"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumePrimaryBlockingIssueAvailable"));
        assertEquals("compatibility-mismatch", metadata.get("checkpointResumePrimaryBlockingIssueKind"));
        assertEquals(
                "checkpoint-resume-compatibility-mismatch",
                metadata.get("checkpointResumePrimaryBlockingIssueCode"));
        assertEquals("error", metadata.get("checkpointResumePrimaryBlockingIssueSeverity"));
        assertEquals("optimizer", metadata.get("checkpointResumePrimaryBlockingAffectedArtifact"));
        assertEquals("parameter signature mismatch", metadata.get("checkpointResumePrimaryBlockingIssueMessage"));
        assertEquals(
                "use a checkpoint generated by the same trainer configuration or start a fresh run",
                metadata.get("checkpointResumePrimaryBlockingRecommendedAction"));
        assertEquals("scheduler", metadata.get("checkpointResumePrimaryAffectedArtifact"));
        assertEquals(
                "scheduler checkpoint artifact is missing on resume",
                metadata.get("checkpointResumePrimaryIssueMessage"));
        assertEquals(
                "restore the missing artifact or resume without checkpoint state",
                metadata.get("checkpointResumePrimaryRecommendedAction"));
        assertEquals(
                Map.of(
                        "missing-artifact", 1,
                        "compatibility-mismatch", 1,
                        "manifest-entry-missing", 1),
                metadata.get("checkpointResumeIssueCountsByKind"));
        assertEquals(
                Map.of(
                        "missing-artifact", "warning",
                        "compatibility-mismatch", "error",
                        "manifest-entry-missing", "warning"),
                metadata.get("checkpointResumeIssueSeveritiesByKind"));
        assertEquals(
                Map.of(
                        "missing-artifact", false,
                        "compatibility-mismatch", true,
                        "manifest-entry-missing", false),
                metadata.get("checkpointResumeIssueBlockingByKind"));
        assertEquals(
                Map.of(
                        "missing-artifact", List.of("scheduler"),
                        "compatibility-mismatch", List.of("optimizer"),
                        "manifest-entry-missing", List.of("runtime")),
                metadata.get("checkpointResumeIssueArtifactsByKind"));
        assertEquals(
                List.of(
                        issue(
                                "missing-artifact",
                                "checkpoint-resume-artifact-missing",
                                "warning",
                                false,
                                "scheduler",
                                "scheduler checkpoint artifact is missing on resume",
                                "restore the missing artifact or resume without checkpoint state"),
                        issue(
                                "compatibility-mismatch",
                                "checkpoint-resume-compatibility-mismatch",
                                "error",
                                true,
                                "optimizer",
                                "parameter signature mismatch",
                                "use a checkpoint generated by the same trainer configuration or start a fresh run"),
                        issue(
                                "manifest-entry-missing",
                                "checkpoint-resume-manifest-entry-missing",
                                "warning",
                                false,
                                "runtime",
                                "runtime checkpoint is missing from checkpoint manifest",
                                "restore a complete checkpoint manifest or regenerate the checkpoint set")),
                metadata.get("checkpointResumeIssues"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeComplete"));
        assertEquals("partial", metadata.get("checkpointResumeStatus"));
        assertEquals(List.of("scheduler"), metadata.get("checkpointResumeMissingArtifacts"));
        assertEquals(List.of("runtime"), metadata.get("checkpointResumeManifestEntryMissingArtifacts"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeManifestEntryMissing"));
        assertEquals(Boolean.TRUE, metadata.get("modelCheckpointLoaded"));
        assertEquals(Boolean.TRUE, metadata.get("modelCheckpointPresent"));
        assertEquals(Boolean.FALSE, metadata.get("modelCheckpointCompatibilityMismatch"));
        assertEquals(Boolean.TRUE, metadata.get("optimizerCheckpointSupported"));
        assertEquals(Boolean.TRUE, metadata.get("optimizerCheckpointSaved"));
        assertEquals(Boolean.TRUE, metadata.get("mixedPrecisionEnabled"));
        assertEquals(32.0, metadata.get("mixedPrecisionLossScale"));
        assertEquals(32.0, metadata.get("mixedPrecisionGradScalerState.scale"));
        assertEquals(Boolean.TRUE, metadata.get("gradScalerCheckpointSupported"));
        assertEquals(5, metadata.get("learningRateSchedulerStepCount"));
        assertEquals("accuracy", metadata.get("learningRateSchedulerMonitor"));
        assertEquals(0.001, metadata.get("learningRate"));
        assertEquals(Boolean.TRUE, metadata.get("trainingHistorySaved"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointManifestIntegrityMismatch"));
        assertEquals(Boolean.FALSE, metadata.get("runtimeCheckpointResumeAllowed"));
        assertEquals(Boolean.TRUE, metadata.get("runtimeCheckpointResumeSkipped"));
        assertEquals(
                "runtime-checkpoint-integrity-mismatch",
                metadata.get("runtimeCheckpointResumeDecision"));
        assertEquals(
                "skip runtime checkpoint and rebuild runtime state from trainer artifacts",
                metadata.get("runtimeCheckpointRecommendedAction"));
        assertEquals(Boolean.FALSE, runtimeCheckpointResumePlan(metadata).get("resumeAllowed"));
        assertEquals(
                "runtime-checkpoint-integrity-mismatch",
                runtimeCheckpointResumePlan(metadata).get("decision"));
        assertEquals("failed", metadata.get("trainingRunHealthStatus"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunHealthy"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunBlockingIssueDetected"));
        assertEquals(Boolean.FALSE, metadata.get("trainingRunGatePassed"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunPrimaryIssueAvailable"));
        assertEquals(
                "checkpoint-resume-compatibility-mismatch",
                metadata.get("trainingRunPrimaryIssueCode"));
        assertEquals(Boolean.TRUE, metadata.get("trainingRunPrimaryBlockingIssueAvailable"));
        assertEquals(
                "checkpoint-resume-compatibility-mismatch",
                metadata.get("trainingRunPrimaryBlockingIssueCode"));
        assertEquals(2, metadata.get("trainingRunIssueCount"));
        assertEquals(
                List.of(
                        "checkpoint-resume-compatibility-mismatch",
                        "runtime-checkpoint-integrity-mismatch"),
                metadata.get("trainingRunIssueCodes"));
        assertEquals(Map.of("checkpoint-resume", 1, "runtime-checkpoint", 1), metadata.get("trainingRunIssueCountsByKind"));
        assertEquals(Map.of("error", 1, "warning", 1), metadata.get("trainingRunIssueCountsBySeverity"));
        assertEquals(Boolean.TRUE, metadata.get("earlyStoppingEnabled"));
        assertEquals("validationLoss", metadata.get("earlyStoppingMonitor"));
        assertEquals(Boolean.TRUE, metadata.get("metricsEnabled"));
        assertEquals(0.91, metadata.get("trainMetric.accuracy"));
        assertEquals("steady", metadata.get("validationMetricDetails.comment"));
        assertEquals(Boolean.TRUE, metadata.get("dataLoaderPlanMetadataCaptured"));
        assertEquals("tensor", metadata.get("trainLoaderPlan.kind"));
        assertEquals(3, metadata.get("trainLoaderPlan.batchCount"));
        assertEquals(6, metadata.get("trainLoaderPlan.sampleCount"));
        assertEquals("healthy", metadata.get("dataLoaderPlanHealthStatus"));
        assertEquals(Boolean.TRUE, metadata.get("dataLoaderPlanHealthGatePassed"));
        assertEquals(0, metadata.get("dataLoaderPlanHealthIssueCount"));
        assertEquals(0, metadata.get("trainLoaderPlan.droppedSampleCount"));
        assertEquals(Boolean.TRUE, metadata.get("dataDistributionDiagnosticsEnabled"));
        assertEquals(List.of(2, 2), metadata.get("trainDataDistribution.classCounts"));
        assertEquals("healthy", metadata.get("dataDistributionHealthStatus"));
        assertEquals(Boolean.TRUE, metadata.get("dataDistributionHealthGatePassed"));
        assertEquals(0, metadata.get("dataDistributionHealthIssueCount"));
        assertEquals(2L, metadata.get("runtimeProfile.train.forward.count"));
        assertEquals(5.0, (double) metadata.get("runtimeProfile.train.forward.totalMillis"), 1e-12);
        assertEquals(Boolean.TRUE, metadata.get("generalizationGapAvailable"));
        assertEquals(-0.11, (double) metadata.get("latestGeneralizationGap"), 1e-12);
        assertEquals(0.23 / 0.34, (double) metadata.get("latestValidationToTrainLossRatio"), 1e-12);
        assertEquals(Boolean.FALSE, metadata.get("latestValidationLossAboveTrainLoss"));
        assertEquals(Boolean.TRUE, metadata.get("latestGeneralizationGapDeltaAvailable"));
        assertEquals(-0.01, (double) metadata.get("latestGeneralizationGapDelta"), 1e-12);
        assertEquals("decreasing", metadata.get("latestGeneralizationGapTrend"));
        assertEquals(Boolean.FALSE, metadata.get("latestGeneralizationGapIncreasing"));
        assertEquals(Boolean.TRUE, metadata.get("latestTrainLossDeltaAvailable"));
        assertEquals(-0.16, (double) metadata.get("latestTrainLossDelta"), 1e-12);
        assertEquals(Boolean.TRUE, metadata.get("latestTrainLossImproved"));
        assertEquals(Boolean.TRUE, metadata.get("latestValidationLossDeltaAvailable"));
        assertEquals(-0.17, (double) metadata.get("latestValidationLossDelta"), 1e-12);
        assertEquals(Boolean.TRUE, metadata.get("latestValidationLossImproved"));
        assertEquals(Boolean.TRUE, metadata.get("latestTrainLossSlopeAvailable"));
        assertEquals(-0.14, (double) metadata.get("latestTrainLossSlopePerEpoch"), 1e-12);
        assertEquals("improving", metadata.get("latestTrainLossTrend"));
        assertEquals(3, metadata.get("latestTrainLossSlopeWindowSize"));
        assertEquals(Boolean.TRUE, metadata.get("latestValidationLossSlopeAvailable"));
        assertEquals(-0.14, (double) metadata.get("latestValidationLossSlopePerEpoch"), 1e-12);
        assertEquals("improving", metadata.get("latestValidationLossTrend"));
        assertEquals(3, metadata.get("latestValidationLossSlopeWindowSize"));
        assertEquals(Boolean.TRUE, metadata.get("latestTrainLossWindowStatsAvailable"));
        assertEquals(3, metadata.get("latestTrainLossWindowStatsSize"));
        assertEquals(trainWindowMean, (double) metadata.get("latestTrainLossWindowMean"), 1e-12);
        assertEquals(trainWindowStdDev, (double) metadata.get("latestTrainLossWindowStdDev"), 1e-12);
        assertEquals(
                trainWindowStdDev / trainWindowMean,
                (double) metadata.get("latestTrainLossWindowCoefficientOfVariation"),
                1e-12);
        assertEquals(Boolean.TRUE, metadata.get("latestValidationLossWindowStatsAvailable"));
        assertEquals(3, metadata.get("latestValidationLossWindowStatsSize"));
        assertEquals(validationWindowMean, (double) metadata.get("latestValidationLossWindowMean"), 1e-12);
        assertEquals(validationWindowStdDev, (double) metadata.get("latestValidationLossWindowStdDev"), 1e-12);
        assertEquals(
                validationWindowStdDev / validationWindowMean,
                (double) metadata.get("latestValidationLossWindowCoefficientOfVariation"),
                1e-12);
        assertEquals(Boolean.TRUE, metadata.get("latestTrainLossBestAvailable"));
        assertEquals(0.34, metadata.get("latestTrainLossBest"));
        assertEquals(2, metadata.get("latestTrainLossBestEpoch"));
        assertEquals(0, metadata.get("latestTrainLossNonImprovingStreak"));
        assertEquals(Boolean.TRUE, metadata.get("latestTrainLossBestAtLatestEpoch"));
        assertEquals(Boolean.TRUE, metadata.get("latestValidationLossBestAvailable"));
        assertEquals(0.23, metadata.get("latestValidationLossBest"));
        assertEquals(2, metadata.get("latestValidationLossBestEpoch"));
        assertEquals(0, metadata.get("latestValidationLossNonImprovingStreak"));
        assertEquals(Boolean.TRUE, metadata.get("latestValidationLossBestAtLatestEpoch"));
        assertEquals(Boolean.TRUE, metadata.get("validationProgressAvailable"));
        assertEquals(0.11, (double) metadata.get("latestValidationLossDeltaFromBest"), 1e-12);
        assertEquals(0.23 / 0.12, (double) metadata.get("latestValidationLossRatioToBest"), 1e-12);
        assertEquals(0, metadata.get("epochsSinceBestValidation"));
        assertEquals(Boolean.FALSE, metadata.get("latestValidationLossIsBest"));
        assertEquals(3, metadata.get("epochHistorySize"));
        assertEquals(4, metadata.get("gradientAccumulationSteps"));
        assertEquals(2, metadata.get("pendingGradientAccumulationBatches"));
        assertEquals(7, metadata.get("optimizerStepCount"));
        assertEquals(5, metadata.get("parameterUpdateDiagnosticsIntervalSteps"));
        assertEquals(Boolean.TRUE, metadata.get("parameterUpdateDiagnosticsSampled"));
        assertEquals(Boolean.TRUE, metadata.get("gradientClipEnabled"));
        assertEquals(Boolean.TRUE, metadata.get("gradientClipNormEnabled"));
        assertEquals(1.5, metadata.get("gradientClipNormThreshold"));
        assertEquals(Boolean.TRUE, metadata.get("gradientClipValueEnabled"));
        assertEquals(0.75, metadata.get("gradientClipValueThreshold"));
        assertEquals(4.0, metadata.get("latestGradientL2NormBeforeClip"));
        assertEquals(0.4, metadata.get("latestGradientMeanAbsBeforeClip"));
        assertEquals(0.1, metadata.get("latestGradientMeanAbs"));
        assertEquals(1.2, metadata.get("latestGradientRmsBeforeClip"));
        assertEquals(0.3, metadata.get("latestGradientRms"));
        assertEquals(1L, metadata.get("latestGradientZeroCount"));
        assertEquals(0.1, metadata.get("latestGradientZeroFraction"));
        assertEquals(10L, metadata.get("latestGradientFiniteCount"));
        assertEquals(0L, metadata.get("latestGradientNonFiniteCount"));
        assertEquals(0.0, metadata.get("latestGradientNonFiniteFraction"));
        assertEquals(0.25, metadata.get("latestGradientClipScale"));
        assertEquals(8.0, metadata.get("latestParameterL2Norm"));
        assertEquals(0.8, metadata.get("latestParameterMeanAbs"));
        assertEquals(2.0, metadata.get("latestParameterRms"));
        assertEquals(3L, metadata.get("latestParameterZeroCount"));
        assertEquals(0.3, metadata.get("latestParameterZeroFraction"));
        assertEquals(10L, metadata.get("latestParameterFiniteCount"));
        assertEquals(0L, metadata.get("latestParameterNonFiniteCount"));
        assertEquals(0.0, metadata.get("latestParameterNonFiniteFraction"));
        assertEquals(0.125, metadata.get("latestGradientToParameterL2Ratio"));
        assertEquals(0.125, metadata.get("latestGradientToParameterMaxAbsRatio"));
        assertEquals(0.125, metadata.get("latestGradientToParameterMeanAbsRatio"));
        assertEquals(0.15, metadata.get("latestGradientToParameterRmsRatio"));
        assertEquals(Boolean.TRUE, metadata.get("parameterUpdateDiagnosticsEnabled"));
        assertEquals(0.5, metadata.get("latestParameterUpdateL2Norm"));
        assertEquals(0.25, metadata.get("latestParameterUpdateMaxAbs"));
        assertEquals(0.05, metadata.get("latestParameterUpdateMeanAbs"));
        assertEquals(0.1, metadata.get("latestParameterUpdateRms"));
        assertEquals(2, metadata.get("latestParameterUpdateCount"));
        assertEquals(10L, metadata.get("latestParameterUpdateValueCount"));
        assertEquals(8L, metadata.get("latestParameterUpdateZeroCount"));
        assertEquals(0.8, metadata.get("latestParameterUpdateZeroFraction"));
        assertEquals(10L, metadata.get("latestParameterUpdateFiniteCount"));
        assertEquals(0L, metadata.get("latestParameterUpdateNonFiniteCount"));
        assertEquals(0.0, metadata.get("latestParameterUpdateNonFiniteFraction"));
        assertEquals(0.0625, metadata.get("latestParameterUpdateToParameterL2Ratio"));
        assertEquals(0.25 / 6.0, (double) metadata.get("latestParameterUpdateToParameterMaxAbsRatio"), 1e-12);
        assertEquals(0.0625, metadata.get("latestParameterUpdateToParameterMeanAbsRatio"));
        assertEquals(0.05, metadata.get("latestParameterUpdateToParameterRmsRatio"));
        assertEquals(0.5, metadata.get("latestParameterUpdateToGradientL2Ratio"));
        assertEquals(1.0 / 3.0, (double) metadata.get("latestParameterUpdateToGradientMaxAbsRatio"), 1e-12);
        assertEquals(0.5, metadata.get("latestParameterUpdateToGradientMeanAbsRatio"));
        assertEquals(1.0 / 3.0, (double) metadata.get("latestParameterUpdateToGradientRmsRatio"), 1e-12);
        assertEquals(2L, metadata.get("trainBatchCount"));
        assertEquals(5.0, metadata.get("trainSamplesPerSecond"));
        assertEquals("metal", metadata.get("requestedDevice"));
        assertEquals("metal", metadata.get("executionBackend"));
        assertEquals(3L, metadata.get("acceleratedMatmulCallsDelta"));
        assertTrue(((String) metadata.get("modelCheckpointFile")).endsWith("model.safetensors"));
        assertEquals(Boolean.FALSE, metadata.get("nonFiniteDetected"));

        assertThrows(UnsupportedOperationException.class, () -> summary.metadata().put("late", true));
    }

    @Test
    void failureStateCanPublishTerminalStopReasonThroughAssembler() throws Exception {
        TrainerFailureState failureState = new TrainerFailureState();
        failureState.recordNonFinite("train", "gradient", Double.NaN, "gradient", true);

        TrainingSummary summary = TrainerSummaryAssembler.enrich(
                new TrainingSummary(1, Double.NaN, -1, 1.0, null, 10L, Map.of()),
                request(tempDir, failureState));

        Map<String, Object> metadata = summary.metadata();
        assertEquals(Boolean.TRUE, metadata.get("nonFiniteDetected"));
        assertEquals("gradient", metadata.get("nonFiniteKind"));
        assertEquals("non-finite-train-gradient", metadata.get("stopReason"));
        assertEquals(Boolean.TRUE, metadata.get("nonFiniteOptimizerStepSkipped"));
        assertEquals(Boolean.FALSE, metadata.get("generalizationGapAvailable"));
        assertEquals(Boolean.FALSE, metadata.get("validationProgressAvailable"));
    }

    private static TrainerSummaryAssembler.Request request(
            Path tempDir,
            TrainerFailureState failureState) throws Exception {
        Path model = Files.writeString(tempDir.resolve("model.safetensors"), "model");
        Path metadata = Files.writeString(tempDir.resolve("model.properties"), "metadata");
        Path best = Files.writeString(tempDir.resolve("best.safetensors"), "best");
        Path optimizer = Files.writeString(tempDir.resolve("optimizer.json"), "{}");
        Path scheduler = Files.writeString(tempDir.resolve("scheduler.json"), "{}");
        Path gradScaler = Files.writeString(tempDir.resolve("grad-scaler.json"), "{}");
        Path history = Files.writeString(tempDir.resolve("history.csv"), "epoch");
        Path report = Files.writeString(tempDir.resolve("report.json"), "{}");
        Path manifest = Files.writeString(tempDir.resolve("manifest.properties"), "manifest");
        Path runtime = Files.writeString(tempDir.resolve("runtime.json"), "{}");

        return new TrainerSummaryAssembler.Request(
                new TrainerSummaryAssembler.Resume(
                        true,
                        List.of("scheduler"),
                        List.of("optimizer: parameter signature mismatch"),
                        List.of("runtime")),
                new TrainerSummaryAssembler.ModelCheckpoint(model, false, true, true, null, null, false),
                new TrainerSummaryAssembler.Artifact(metadata, false, true, true, null, null),
                new TrainerSummaryAssembler.BestModel(
                        true,
                        true,
                        best,
                        "accuracy",
                        CanonicalTrainer.BestModelMonitorMode.MAX,
                        new TrainerBestModelCheckpointMetadata.State(true, false, 2, 0.23, 0.92),
                        null,
                        null),
                new TrainerSummaryAssembler.StateCheckpoint(
                        true,
                        true,
                        optimizer,
                        false,
                        true,
                        true,
                        null,
                        null),
                new TrainerSummaryAssembler.MixedPrecision(
                        true,
                        32.0,
                        false,
                        1,
                        Map.of("scale", 32.0),
                        new TrainerMixedPrecisionMetadata.GradScalerCheckpoint(
                                true,
                                true,
                                true,
                                gradScaler,
                                false,
                                true,
                                true,
                                null,
                                null,
                                false)),
                new TrainerSummaryAssembler.Scheduler(
                        true,
                        CanonicalTrainer.SchedulerStepUnit.VALIDATION.name(),
                        5,
                        "cosine",
                        "accuracy",
                        true,
                        Map.of("lastEpoch", 5),
                        0.001,
                        new TrainerLearningRateSchedulerMetadata.SchedulerCheckpoint(
                                true,
                                true,
                                true,
                                scheduler,
                                true,
                                false,
                                true,
                                "missing on resume",
                                null)),
                new TrainerSummaryAssembler.RuntimeArtifacts(
                        new TrainerRuntimeArtifactMetadata.Artifact(
                                true,
                                history,
                                false,
                                true,
                                true,
                                null,
                                null),
                        new TrainerRuntimeArtifactMetadata.SaveOnlyArtifact(
                                true,
                                report,
                                true,
                                null),
                        new TrainerRuntimeArtifactMetadata.Artifact(
                                true,
                                manifest,
                                false,
                                true,
                                true,
                                null,
                                null),
                        true,
                        new TrainerRuntimeArtifactMetadata.RuntimeCheckpoint(
                                runtime,
                                true,
                                true,
                                "runtime mismatch")),
                new TrainerSummaryAssembler.EarlyStopping(
                        3,
                        0.01,
                        "validationLoss",
                        CanonicalTrainer.BestModelMonitorMode.MIN,
                        false,
                        new TrainerEarlyStoppingMetadata.MonitorState(2, 0.12, 0.23, 1),
                        false,
                        -1),
                failureState,
                new TrainerSummaryAssembler.Metrics(
                        true,
                        Map.of("accuracy", 0.91),
                        Map.of("accuracy", 0.89),
                        Map.of("comment", "warm"),
                        Map.of("comment", "steady")),
                new TrainerSummaryAssembler.DataLoaderPlans(Map.ofEntries(
                        Map.entry("dataLoaderPlanMetadataCaptured", Boolean.TRUE),
                        Map.entry("trainLoaderPlan.available", Boolean.TRUE),
                        Map.entry("trainLoaderPlan.kind", "tensor"),
                        Map.entry("trainLoaderPlan.batchCount", 3),
                        Map.entry("trainLoaderPlan.batchSize", 2),
                        Map.entry("trainLoaderPlan.sampleCount", 6),
                        Map.entry("trainLoaderPlan.sampled", Boolean.FALSE),
                        Map.entry("trainLoaderPlan.dropLast", Boolean.FALSE),
                        Map.entry("trainLoaderPlan.shuffle", Boolean.TRUE),
                        Map.entry("trainLoaderPlan.reshuffleEachEpoch", Boolean.TRUE),
                        Map.entry("trainLoaderPlan.hasShuffleSeed", Boolean.TRUE),
                        Map.entry("trainLoaderPlan.sampleCoverageRatio", 1.0),
                        Map.entry("validationLoaderPlan.available", Boolean.FALSE),
                        Map.entry("validationLoaderPlan.skipReason", "no-loader"))),
                new TrainerSummaryAssembler.DataDistribution(Map.ofEntries(
                        Map.entry("dataDistributionDiagnosticsEnabled", Boolean.TRUE),
                        Map.entry("trainDataDistribution.available", Boolean.TRUE),
                        Map.entry("trainDataDistribution.kind", "classification"),
                        Map.entry("trainDataDistribution.sampleCount", 4),
                        Map.entry("trainDataDistribution.batchCount", 2),
                        Map.entry("trainDataDistribution.numClasses", 2),
                        Map.entry("trainDataDistribution.classCounts", List.of(2, 2)),
                        Map.entry("trainDataDistribution.missingClassCount", 0),
                        Map.entry("trainDataDistribution.imbalanceRatio", 1.0),
                        Map.entry("trainDataDistribution.normalizedEntropy", 1.0),
                        Map.entry("validationDataDistribution.available", Boolean.FALSE),
                        Map.entry("validationDataDistribution.skipReason", "no-loader"),
                        Map.entry("dataDistributionDrift.available", Boolean.FALSE),
                        Map.entry("dataDistributionDrift.skipped", Boolean.TRUE),
                        Map.entry("dataDistributionDrift.skipReason", "missing-compatible-distributions"))),
                new TrainerSummaryAssembler.History(
                        List.of(
                                Map.of("epoch", 0, "trainLoss", 0.62, "validationLoss", 0.51),
                                Map.of("epoch", 1, "trainLoss", 0.5, "validationLoss", 0.4),
                                Map.of("epoch", 2, "trainLoss", 0.34, "validationLoss", 0.23)),
                        3),
                new TrainerSummaryAssembler.Optimization(
                        4,
                        2,
                        7,
                        TrainerGradientClipConfig.of(1.5, 0.75),
                        5,
                        new TrainerOptimizationMetadata.GradientDiagnostics(
                                4.0,
                                1.0,
                                3.0,
                                0.75,
                                0.4,
                                0.1,
                                1.2,
                                0.3,
                                2,
                                10,
                                1,
                                0.1,
                                0.25,
                                true),
                        new TrainerOptimizationMetadata.ParameterDiagnostics(
                                8.0,
                                6.0,
                                0.8,
                                2.0,
                                2,
                                10,
                                3,
                                0.3),
                        new TrainerOptimizationMetadata.UpdateDiagnostics(
                                true,
                                0.5,
                                0.25,
                                0.05,
                                0.1,
                                2,
                                10,
                                8,
                                0.8)),
                new TrainerSummaryAssembler.Throughput(
                        new ThroughputSnapshot(2, 10, 20, 5, 2_000_000_000L),
                        new ThroughputSnapshot(1, 4, 8, 2, 1_000_000_000L)),
                new TrainerSummaryAssembler.RuntimeProfile(Map.of(
                        "runtimeProfile.train.forward.count", 2L,
                        "runtimeProfile.train.forward.totalMillis", 5.0)),
                new TrainerSummaryAssembler.AccelerationInfo(
                        "metal",
                        new Acceleration.BackendStatus("metal", "Apple GPU", true, true, 8L),
                        new Acceleration.BackendStatus("metal", "Apple GPU", true, true, 5L)),
                new TrainerSummaryAssembler.References(
                        new TrainerSummaryReferenceMetadata.Paths(
                                model,
                                metadata,
                                best,
                                optimizer,
                                scheduler,
                                gradScaler,
                                true,
                                history,
                                report,
                                runtime,
                                manifest),
                        new TrainerSummaryReferenceMetadata.Errors(
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                "missing on resume",
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                null,
                null,
                "runtime mismatch")));
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> runtimeCheckpointResumePlan(Map<String, Object> metadata) {
        return (Map<String, Object>) metadata.get("runtimeCheckpointResumePlan");
    }

    private static Map<String, Object> issue(
            String kind,
            String code,
            String severity,
            boolean blocking,
            String artifact,
            String message,
            String action) {
        return Map.of(
                "kind", kind,
                "code", code,
                "severity", severity,
                "blocking", blocking,
                "artifact", artifact,
                "message", message,
                "action", action);
    }
}
