package tech.kayys.tafkir.ml.train;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class TrainerSummaryMetadataTest {

    @Test
    void checkpointResumeOverviewMarksPartialOnlyWhenResumeWasRequested() {
        Map<String, Object> metadata = new HashMap<>();

        TrainerSummaryMetadata.putCheckpointResumeOverview(
                metadata,
                false,
                List.of("optimizer"),
                List.of("model: signature mismatch"),
                List.of("scheduler"));

        assertEquals(List.of("optimizer"), metadata.get("checkpointResumeMissingArtifacts"));
        assertEquals(List.of("model: signature mismatch"), metadata.get("checkpointResumeCompatibilityMismatches"));
        assertEquals(List.of("model: signature mismatch"), metadata.get("checkpointCompatibilityMismatches"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointCompatibilityMismatch"));
        assertEquals(List.of("scheduler"), metadata.get("checkpointResumeManifestEntryMissingArtifacts"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeManifestEntryMissing"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeIssueDetected"));
        assertEquals(3, metadata.get("checkpointResumeIssueCount"));
        assertEquals(
                List.of("missing-artifact", "compatibility-mismatch", "manifest-entry-missing"),
                metadata.get("checkpointResumeIssueKinds"));
        assertEquals(List.of("optimizer", "model", "scheduler"), metadata.get("checkpointResumeAffectedArtifacts"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeBlockingIssueDetected"));
        assertEquals(1, metadata.get("checkpointResumeBlockingIssueCount"));
        assertEquals(List.of("compatibility-mismatch"), metadata.get("checkpointResumeBlockingIssueKinds"));
        assertEquals(
                List.of(issue(
                        "compatibility-mismatch",
                        "checkpoint-resume-compatibility-mismatch",
                        "error",
                        true,
                        "model",
                        "signature mismatch",
                        "use a checkpoint generated by the same trainer configuration or start a fresh run")),
                metadata.get("checkpointResumeBlockingIssues"));
        assertEquals(
                List.of(
                        "checkpoint-resume-artifact-missing",
                        "checkpoint-resume-compatibility-mismatch",
                        "checkpoint-resume-manifest-entry-missing"),
                metadata.get("checkpointResumeIssueCodes"));
        assertEquals(List.of("warning", "error"), metadata.get("checkpointResumeIssueSeverities"));
        assertEquals(
                List.of(
                        "restore the missing artifact or resume without checkpoint state",
                        "use a checkpoint generated by the same trainer configuration or start a fresh run",
                        "restore a complete checkpoint manifest or regenerate the checkpoint set"),
                metadata.get("checkpointResumeRecommendedActions"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumePrimaryIssueAvailable"));
        assertEquals("missing-artifact", metadata.get("checkpointResumePrimaryIssueKind"));
        assertEquals("checkpoint-resume-artifact-missing", metadata.get("checkpointResumePrimaryIssueCode"));
        assertEquals("warning", metadata.get("checkpointResumePrimaryIssueSeverity"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumePrimaryIssueBlocking"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumePrimaryBlockingIssueAvailable"));
        assertEquals("compatibility-mismatch", metadata.get("checkpointResumePrimaryBlockingIssueKind"));
        assertEquals(
                "checkpoint-resume-compatibility-mismatch",
                metadata.get("checkpointResumePrimaryBlockingIssueCode"));
        assertEquals("error", metadata.get("checkpointResumePrimaryBlockingIssueSeverity"));
        assertEquals("model", metadata.get("checkpointResumePrimaryBlockingAffectedArtifact"));
        assertEquals("signature mismatch", metadata.get("checkpointResumePrimaryBlockingIssueMessage"));
        assertEquals(
                "use a checkpoint generated by the same trainer configuration or start a fresh run",
                metadata.get("checkpointResumePrimaryBlockingRecommendedAction"));
        assertEquals("optimizer", metadata.get("checkpointResumePrimaryAffectedArtifact"));
        assertEquals(
                "optimizer checkpoint artifact is missing on resume",
                metadata.get("checkpointResumePrimaryIssueMessage"));
        assertEquals(
                "restore the missing artifact or resume without checkpoint state",
                metadata.get("checkpointResumePrimaryRecommendedAction"));
        assertEquals(
                Map.of(
                        "missing-artifact", 1,
                        "compatibility-mismatch", 1,
                        "manifest-entry-missing", 1),
                metadata.get("checkpointResumeIssueCountsByKind"));
        assertEquals(
                Map.of(
                        "missing-artifact", "warning",
                        "compatibility-mismatch", "error",
                        "manifest-entry-missing", "warning"),
                metadata.get("checkpointResumeIssueSeveritiesByKind"));
        assertEquals(
                Map.of(
                        "missing-artifact", false,
                        "compatibility-mismatch", true,
                        "manifest-entry-missing", false),
                metadata.get("checkpointResumeIssueBlockingByKind"));
        assertEquals(
                Map.of(
                        "missing-artifact", List.of("optimizer"),
                        "compatibility-mismatch", List.of("model"),
                        "manifest-entry-missing", List.of("scheduler")),
                metadata.get("checkpointResumeIssueArtifactsByKind"));
        assertEquals(
                List.of(
                        issue(
                                "missing-artifact",
                                "checkpoint-resume-artifact-missing",
                                "warning",
                                false,
                                "optimizer",
                                "optimizer checkpoint artifact is missing on resume",
                                "restore the missing artifact or resume without checkpoint state"),
                        issue(
                                "compatibility-mismatch",
                                "checkpoint-resume-compatibility-mismatch",
                                "error",
                                true,
                                "model",
                                "signature mismatch",
                                "use a checkpoint generated by the same trainer configuration or start a fresh run"),
                        issue(
                                "manifest-entry-missing",
                                "checkpoint-resume-manifest-entry-missing",
                                "warning",
                                false,
                                "scheduler",
                                "scheduler checkpoint is missing from checkpoint manifest",
                                "restore a complete checkpoint manifest or regenerate the checkpoint set")),
                metadata.get("checkpointResumeIssues"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeComplete"));
        assertEquals("not-requested", metadata.get("checkpointResumeStatus"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeStateUsable"));
        assertEquals("not-requested", metadata.get("checkpointResumeRecommendedMode"));
        assertEquals("run without checkpoint resume", metadata.get("checkpointResumeNextAction"));
        Map<String, Object> plan = immutableCheckpointResumePlan(metadata);
        assertEquals(1, plan.get("version"));
        assertEquals(Boolean.FALSE, plan.get("requested"));
        assertEquals("not-requested", plan.get("status"));
        assertEquals(Boolean.FALSE, plan.get("complete"));
        assertEquals(Boolean.FALSE, plan.get("stateUsable"));
        assertEquals("not-requested", plan.get("recommendedMode"));
        assertEquals("run without checkpoint resume", plan.get("nextAction"));
        assertEquals(Boolean.TRUE, plan.get("issueDetected"));
        assertEquals(3, plan.get("issueCount"));
        assertEquals(
                List.of("missing-artifact", "compatibility-mismatch", "manifest-entry-missing"),
                plan.get("issueKinds"));
        assertEquals(List.of("optimizer", "model", "scheduler"), plan.get("affectedArtifacts"));
        assertEquals(Boolean.TRUE, plan.get("blockingIssueDetected"));
        assertEquals(1, plan.get("blockingIssueCount"));
        assertEquals(List.of("compatibility-mismatch"), plan.get("blockingIssueKinds"));
        assertEquals(Boolean.TRUE, plan.get("primaryIssueAvailable"));
        assertEquals("missing-artifact", plan.get("primaryIssueKind"));
        assertEquals("checkpoint-resume-artifact-missing", plan.get("primaryIssueCode"));
        assertEquals("warning", plan.get("primaryIssueSeverity"));
        assertEquals(Boolean.FALSE, plan.get("primaryIssueBlocking"));
        assertEquals("optimizer", plan.get("primaryAffectedArtifact"));
        assertEquals(
                "optimizer checkpoint artifact is missing on resume",
                plan.get("primaryIssueMessage"));
        assertEquals(
                "restore the missing artifact or resume without checkpoint state",
                plan.get("primaryRecommendedAction"));
        assertEquals(Boolean.TRUE, plan.get("primaryBlockingIssueAvailable"));
        assertEquals("compatibility-mismatch", plan.get("primaryBlockingIssueKind"));
        assertEquals(
                "checkpoint-resume-compatibility-mismatch",
                plan.get("primaryBlockingIssueCode"));
        assertEquals("error", plan.get("primaryBlockingIssueSeverity"));
        assertEquals("model", plan.get("primaryBlockingAffectedArtifact"));
        assertEquals("signature mismatch", plan.get("primaryBlockingIssueMessage"));
        assertEquals(
                "use a checkpoint generated by the same trainer configuration or start a fresh run",
                plan.get("primaryBlockingRecommendedAction"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumePartial"));
    }

    @Test
    void checkpointResumeOverviewMarksCompleteWhenRequestedWithoutIssues() {
        Map<String, Object> metadata = new HashMap<>();

        TrainerSummaryMetadata.putCheckpointResumeOverview(
                metadata,
                true,
                List.of(),
                List.of(),
                List.of());

        assertEquals(List.of(), metadata.get("checkpointResumeMissingArtifacts"));
        assertEquals(List.of(), metadata.get("checkpointResumeCompatibilityMismatches"));
        assertEquals(List.of(), metadata.get("checkpointResumeManifestEntryMissingArtifacts"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeIssueDetected"));
        assertEquals(0, metadata.get("checkpointResumeIssueCount"));
        assertEquals(List.of(), metadata.get("checkpointResumeIssueKinds"));
        assertEquals(List.of(), metadata.get("checkpointResumeAffectedArtifacts"));
        assertEquals(List.of(), metadata.get("checkpointResumeIssues"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeBlockingIssueDetected"));
        assertEquals(0, metadata.get("checkpointResumeBlockingIssueCount"));
        assertEquals(List.of(), metadata.get("checkpointResumeBlockingIssueKinds"));
        assertEquals(List.of(), metadata.get("checkpointResumeBlockingIssues"));
        assertEquals(List.of(), metadata.get("checkpointResumeIssueCodes"));
        assertEquals(List.of(), metadata.get("checkpointResumeIssueSeverities"));
        assertEquals(List.of(), metadata.get("checkpointResumeRecommendedActions"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumePrimaryIssueAvailable"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryIssueKind"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryIssueCode"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryIssueSeverity"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryIssueBlocking"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumePrimaryBlockingIssueAvailable"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryBlockingIssueKind"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryBlockingIssueCode"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryBlockingIssueSeverity"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryBlockingAffectedArtifact"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryBlockingIssueMessage"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryBlockingRecommendedAction"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryAffectedArtifact"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryIssueMessage"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryRecommendedAction"));
        assertEquals(Map.of(), metadata.get("checkpointResumeIssueCountsByKind"));
        assertEquals(Map.of(), metadata.get("checkpointResumeIssueSeveritiesByKind"));
        assertEquals(Map.of(), metadata.get("checkpointResumeIssueBlockingByKind"));
        assertEquals(Map.of(), metadata.get("checkpointResumeIssueArtifactsByKind"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeComplete"));
        assertEquals("complete", metadata.get("checkpointResumeStatus"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeStateUsable"));
        assertEquals("complete-resume", metadata.get("checkpointResumeRecommendedMode"));
        assertEquals("continue with restored checkpoint state", metadata.get("checkpointResumeNextAction"));
        Map<String, Object> plan = immutableCheckpointResumePlan(metadata);
        assertEquals(Boolean.TRUE, plan.get("requested"));
        assertEquals("complete", plan.get("status"));
        assertEquals(Boolean.TRUE, plan.get("complete"));
        assertEquals(Boolean.TRUE, plan.get("stateUsable"));
        assertEquals("complete-resume", plan.get("recommendedMode"));
        assertEquals("continue with restored checkpoint state", plan.get("nextAction"));
        assertEquals(Boolean.FALSE, plan.get("issueDetected"));
        assertEquals(0, plan.get("issueCount"));
        assertEquals(List.of(), plan.get("issueKinds"));
        assertEquals(List.of(), plan.get("affectedArtifacts"));
        assertEquals(Boolean.FALSE, plan.get("blockingIssueDetected"));
        assertEquals(0, plan.get("blockingIssueCount"));
        assertEquals(List.of(), plan.get("blockingIssueKinds"));
        assertEquals(Boolean.FALSE, plan.get("primaryIssueAvailable"));
        assertEquals(Boolean.FALSE, plan.get("primaryBlockingIssueAvailable"));
        assertFalse(plan.containsKey("primaryIssueKind"));
        assertFalse(plan.containsKey("primaryBlockingIssueKind"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumePartial"));
    }

    @Test
    void checkpointResumeOverviewRecommendsPartialResumeForNonBlockingIssues() {
        Map<String, Object> metadata = new HashMap<>();

        TrainerSummaryMetadata.putCheckpointResumeOverview(
                metadata,
                true,
                List.of("optimizer"),
                List.of(),
                List.of("scheduler"));

        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeIssueDetected"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeBlockingIssueDetected"));
        assertEquals(0, metadata.get("checkpointResumeBlockingIssueCount"));
        assertEquals(List.of(), metadata.get("checkpointResumeBlockingIssueKinds"));
        assertEquals(List.of(), metadata.get("checkpointResumeBlockingIssues"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeComplete"));
        assertEquals("partial", metadata.get("checkpointResumeStatus"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeStateUsable"));
        assertEquals("partial-resume", metadata.get("checkpointResumeRecommendedMode"));
        assertEquals(
                "continue with partial resume or restore missing checkpoint artifacts",
                metadata.get("checkpointResumeNextAction"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumePartial"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumePrimaryIssueBlocking"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumePrimaryBlockingIssueAvailable"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryBlockingIssueKind"));
        assertFalse(metadata.containsKey("checkpointResumePrimaryBlockingRecommendedAction"));
        Map<String, Object> plan = immutableCheckpointResumePlan(metadata);
        assertEquals("partial", plan.get("status"));
        assertEquals(Boolean.TRUE, plan.get("stateUsable"));
        assertEquals("partial-resume", plan.get("recommendedMode"));
        assertEquals(Boolean.TRUE, plan.get("issueDetected"));
        assertEquals(2, plan.get("issueCount"));
        assertEquals(List.of("missing-artifact", "manifest-entry-missing"), plan.get("issueKinds"));
        assertEquals(List.of("optimizer", "scheduler"), plan.get("affectedArtifacts"));
        assertEquals(Boolean.FALSE, plan.get("blockingIssueDetected"));
        assertEquals(0, plan.get("blockingIssueCount"));
        assertEquals(List.of(), plan.get("blockingIssueKinds"));
        assertEquals(Boolean.TRUE, plan.get("primaryIssueAvailable"));
        assertEquals("missing-artifact", plan.get("primaryIssueKind"));
        assertEquals(Boolean.FALSE, plan.get("primaryIssueBlocking"));
        assertEquals(Boolean.FALSE, plan.get("primaryBlockingIssueAvailable"));
        assertFalse(plan.containsKey("primaryBlockingIssueKind"));
    }

    @Test
    void checkpointResumeOverviewStoresImmutableSnapshots() {
        Map<String, Object> metadata = new HashMap<>();
        List<String> missing = new ArrayList<>(List.of("optimizer"));
        List<String> mismatches = new ArrayList<>(List.of("scheduler"));
        List<String> missingManifestEntries = new ArrayList<>(List.of("gradScaler"));

        TrainerSummaryMetadata.putCheckpointResumeOverview(
                metadata,
                true,
                missing,
                mismatches,
                missingManifestEntries);
        missing.add("late-missing");
        mismatches.add("late-mismatch");
        missingManifestEntries.add("late-manifest-entry");

        assertEquals(List.of("optimizer"), metadata.get("checkpointResumeMissingArtifacts"));
        assertEquals(List.of("scheduler"), metadata.get("checkpointResumeCompatibilityMismatches"));
        assertEquals(List.of("gradScaler"), metadata.get("checkpointResumeManifestEntryMissingArtifacts"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeManifestEntryMissing"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeIssueDetected"));
        assertEquals(3, metadata.get("checkpointResumeIssueCount"));
        assertEquals(
                List.of("missing-artifact", "compatibility-mismatch", "manifest-entry-missing"),
                metadata.get("checkpointResumeIssueKinds"));
        assertEquals(
                List.of("optimizer", "scheduler", "gradScaler"),
                metadata.get("checkpointResumeAffectedArtifacts"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumeBlockingIssueDetected"));
        assertEquals(1, metadata.get("checkpointResumeBlockingIssueCount"));
        assertEquals(List.of("compatibility-mismatch"), metadata.get("checkpointResumeBlockingIssueKinds"));
        assertEquals(
                List.of(issue(
                        "compatibility-mismatch",
                        "checkpoint-resume-compatibility-mismatch",
                        "error",
                        true,
                        "scheduler",
                        "scheduler",
                        "use a checkpoint generated by the same trainer configuration or start a fresh run")),
                metadata.get("checkpointResumeBlockingIssues"));
        assertEquals(
                List.of(
                        "checkpoint-resume-artifact-missing",
                        "checkpoint-resume-compatibility-mismatch",
                        "checkpoint-resume-manifest-entry-missing"),
                metadata.get("checkpointResumeIssueCodes"));
        assertEquals(List.of("warning", "error"), metadata.get("checkpointResumeIssueSeverities"));
        assertEquals(
                List.of(
                        "restore the missing artifact or resume without checkpoint state",
                        "use a checkpoint generated by the same trainer configuration or start a fresh run",
                        "restore a complete checkpoint manifest or regenerate the checkpoint set"),
                metadata.get("checkpointResumeRecommendedActions"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumePrimaryIssueAvailable"));
        assertEquals("missing-artifact", metadata.get("checkpointResumePrimaryIssueKind"));
        assertEquals("checkpoint-resume-artifact-missing", metadata.get("checkpointResumePrimaryIssueCode"));
        assertEquals("warning", metadata.get("checkpointResumePrimaryIssueSeverity"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumePrimaryIssueBlocking"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumePrimaryBlockingIssueAvailable"));
        assertEquals("compatibility-mismatch", metadata.get("checkpointResumePrimaryBlockingIssueKind"));
        assertEquals(
                "checkpoint-resume-compatibility-mismatch",
                metadata.get("checkpointResumePrimaryBlockingIssueCode"));
        assertEquals("error", metadata.get("checkpointResumePrimaryBlockingIssueSeverity"));
        assertEquals("scheduler", metadata.get("checkpointResumePrimaryBlockingAffectedArtifact"));
        assertEquals("scheduler", metadata.get("checkpointResumePrimaryBlockingIssueMessage"));
        assertEquals(
                "use a checkpoint generated by the same trainer configuration or start a fresh run",
                metadata.get("checkpointResumePrimaryBlockingRecommendedAction"));
        assertEquals("optimizer", metadata.get("checkpointResumePrimaryAffectedArtifact"));
        assertEquals(
                "optimizer checkpoint artifact is missing on resume",
                metadata.get("checkpointResumePrimaryIssueMessage"));
        assertEquals(
                "restore the missing artifact or resume without checkpoint state",
                metadata.get("checkpointResumePrimaryRecommendedAction"));
        assertEquals(
                Map.of(
                        "missing-artifact", 1,
                        "compatibility-mismatch", 1,
                        "manifest-entry-missing", 1),
                metadata.get("checkpointResumeIssueCountsByKind"));
        assertEquals(
                Map.of(
                        "missing-artifact", "warning",
                        "compatibility-mismatch", "error",
                        "manifest-entry-missing", "warning"),
                metadata.get("checkpointResumeIssueSeveritiesByKind"));
        assertEquals(
                Map.of(
                        "missing-artifact", false,
                        "compatibility-mismatch", true,
                        "manifest-entry-missing", false),
                metadata.get("checkpointResumeIssueBlockingByKind"));
        assertEquals(
                Map.of(
                        "missing-artifact", List.of("optimizer"),
                        "compatibility-mismatch", List.of("scheduler"),
                        "manifest-entry-missing", List.of("gradScaler")),
                metadata.get("checkpointResumeIssueArtifactsByKind"));
        assertEquals(
                List.of(
                        issue(
                                "missing-artifact",
                                "checkpoint-resume-artifact-missing",
                                "warning",
                                false,
                                "optimizer",
                                "optimizer checkpoint artifact is missing on resume",
                                "restore the missing artifact or resume without checkpoint state"),
                        issue(
                                "compatibility-mismatch",
                                "checkpoint-resume-compatibility-mismatch",
                                "error",
                                true,
                                "scheduler",
                                "scheduler",
                                "use a checkpoint generated by the same trainer configuration or start a fresh run"),
                        issue(
                                "manifest-entry-missing",
                                "checkpoint-resume-manifest-entry-missing",
                                "warning",
                                false,
                                "gradScaler",
                                "gradScaler checkpoint is missing from checkpoint manifest",
                                "restore a complete checkpoint manifest or regenerate the checkpoint set")),
                metadata.get("checkpointResumeIssues"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeComplete"));
        assertEquals("partial", metadata.get("checkpointResumeStatus"));
        assertEquals(Boolean.FALSE, metadata.get("checkpointResumeStateUsable"));
        assertEquals("fresh-start", metadata.get("checkpointResumeRecommendedMode"));
        assertEquals(
                "start a fresh run or choose a compatible checkpoint before resuming",
                metadata.get("checkpointResumeNextAction"));
        assertEquals(Boolean.TRUE, metadata.get("checkpointResumePartial"));
        assertThrows(UnsupportedOperationException.class, () -> immutableMissingArtifacts(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableManifestEntryMissingArtifacts(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableIssueKinds(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableAffectedArtifacts(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableIssues(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableIssues(metadata).getFirst().clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableBlockingIssues(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableBlockingIssues(metadata).getFirst().clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableIssueCodes(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableIssueSeverities(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableBlockingIssueKinds(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableRecommendedActions(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableIssueCountsByKind(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableIssueSeveritiesByKind(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableIssueBlockingByKind(metadata).clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableIssueArtifactsByKind(metadata).clear());
        assertThrows(
                UnsupportedOperationException.class,
                () -> immutableIssueArtifactsByKind(metadata).get("missing-artifact").clear());
        assertThrows(UnsupportedOperationException.class, () -> immutableCheckpointResumePlan(metadata).clear());
        assertThrows(
                UnsupportedOperationException.class,
                () -> immutableCheckpointResumePlanIssueKinds(metadata).clear());
        assertThrows(
                UnsupportedOperationException.class,
                () -> immutableCheckpointResumePlanAffectedArtifacts(metadata).clear());
    }

    @Test
    void optionalPathWritesOnlyWhenPresentAndIncluded() {
        Map<String, Object> metadata = new HashMap<>();

        TrainerSummaryMetadata.putOptionalPath(metadata, "modelCheckpointFile", Path.of("checkpoint.bin"));
        TrainerSummaryMetadata.putOptionalPath(metadata, "optimizerCheckpointFile", null);
        TrainerSummaryMetadata.putOptionalPath(metadata, "gradScalerCheckpointFile", Path.of("grad.bin"), false);

        assertEquals("checkpoint.bin", metadata.get("modelCheckpointFile"));
        assertFalse(metadata.containsKey("optimizerCheckpointFile"));
        assertFalse(metadata.containsKey("gradScalerCheckpointFile"));
    }

    @Test
    void optionalErrorWritesOnlyWhenPresent() {
        Map<String, Object> metadata = new HashMap<>();

        TrainerSummaryMetadata.putOptionalError(metadata, "modelCheckpointLoadError", "bad-shape");
        TrainerSummaryMetadata.putOptionalError(metadata, "modelCheckpointSaveError", null);

        assertEquals("bad-shape", metadata.get("modelCheckpointLoadError"));
        assertFalse(metadata.containsKey("modelCheckpointSaveError"));
    }

    @Test
    void checkpointStatusWritesResumeAndLoadSaveFlags(@TempDir Path tempDir) throws Exception {
        Map<String, Object> metadata = new HashMap<>();
        Path checkpoint = Files.writeString(tempDir.resolve("optimizer.bin"), "state");

        TrainerSummaryMetadata.putSupportedCheckpointStatus(
                metadata,
                "optimizerCheckpoint",
                true,
                true,
                true,
                checkpoint,
                false,
                true,
                false,
                "load-failed",
                null);

        assertEquals(Boolean.TRUE, metadata.get("optimizerCheckpointEnabled"));
        assertEquals(Boolean.TRUE, metadata.get("optimizerCheckpointSupported"));
        assertEquals(Boolean.TRUE, metadata.get("optimizerCheckpointResumeRequested"));
        assertEquals(Boolean.TRUE, metadata.get("optimizerCheckpointPresent"));
        assertEquals(Boolean.FALSE, metadata.get("optimizerCheckpointMissingOnResume"));
        assertEquals(Boolean.TRUE, metadata.get("optimizerCheckpointLoaded"));
        assertEquals(Boolean.FALSE, metadata.get("optimizerCheckpointSaved"));
        assertEquals(Boolean.TRUE, metadata.get("optimizerCheckpointLoadFailed"));
        assertEquals(Boolean.FALSE, metadata.get("optimizerCheckpointSaveFailed"));
    }

    @Test
    void artifactStatusWritesCommonArtifactLifecycleFlags() {
        Map<String, Object> metadata = new HashMap<>();

        TrainerSummaryMetadata.putArtifactStatus(
                metadata,
                "trainingHistory",
                true,
                Path.of("missing-history.csv"),
                true,
                false,
                true,
                null,
                "save-failed");

        assertEquals(Boolean.TRUE, metadata.get("trainingHistoryEnabled"));
        assertEquals(Boolean.FALSE, metadata.get("trainingHistoryPresent"));
        assertEquals(Boolean.TRUE, metadata.get("trainingHistoryMissingOnResume"));
        assertEquals(Boolean.FALSE, metadata.get("trainingHistoryLoaded"));
        assertEquals(Boolean.TRUE, metadata.get("trainingHistorySaved"));
        assertEquals(Boolean.FALSE, metadata.get("trainingHistoryLoadFailed"));
        assertEquals(Boolean.TRUE, metadata.get("trainingHistorySaveFailed"));
    }

    @Test
    void saveOnlyArtifactStatusSkipsLoadFields(@TempDir Path tempDir) throws Exception {
        Map<String, Object> metadata = new HashMap<>();
        Path report = Files.writeString(tempDir.resolve("report.json"), "{}");

        TrainerSummaryMetadata.putSaveOnlyArtifactStatus(
                metadata,
                "trainingReport",
                true,
                report,
                true,
                "write-failed");

        assertEquals(Boolean.TRUE, metadata.get("trainingReportEnabled"));
        assertEquals(Boolean.TRUE, metadata.get("trainingReportPresent"));
        assertEquals(Boolean.TRUE, metadata.get("trainingReportSaved"));
        assertEquals(Boolean.TRUE, metadata.get("trainingReportSaveFailed"));
        assertFalse(metadata.containsKey("trainingReportLoaded"));
        assertFalse(metadata.containsKey("trainingReportLoadFailed"));
        assertFalse(metadata.containsKey("trainingReportMissingOnResume"));
    }

    private static List<?> immutableMissingArtifacts(Map<String, Object> metadata) {
        return (List<?>) metadata.get("checkpointResumeMissingArtifacts");
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> immutableCheckpointResumePlan(Map<String, Object> metadata) {
        return (Map<String, Object>) metadata.get("checkpointResumePlan");
    }

    private static List<?> immutableCheckpointResumePlanIssueKinds(Map<String, Object> metadata) {
        return (List<?>) immutableCheckpointResumePlan(metadata).get("issueKinds");
    }

    private static List<?> immutableCheckpointResumePlanAffectedArtifacts(Map<String, Object> metadata) {
        return (List<?>) immutableCheckpointResumePlan(metadata).get("affectedArtifacts");
    }

    private static List<?> immutableManifestEntryMissingArtifacts(Map<String, Object> metadata) {
        return (List<?>) metadata.get("checkpointResumeManifestEntryMissingArtifacts");
    }

    private static List<?> immutableIssueKinds(Map<String, Object> metadata) {
        return (List<?>) metadata.get("checkpointResumeIssueKinds");
    }

    private static List<?> immutableAffectedArtifacts(Map<String, Object> metadata) {
        return (List<?>) metadata.get("checkpointResumeAffectedArtifacts");
    }

    private static List<?> immutableIssueCodes(Map<String, Object> metadata) {
        return (List<?>) metadata.get("checkpointResumeIssueCodes");
    }

    private static List<?> immutableIssueSeverities(Map<String, Object> metadata) {
        return (List<?>) metadata.get("checkpointResumeIssueSeverities");
    }

    private static List<?> immutableBlockingIssueKinds(Map<String, Object> metadata) {
        return (List<?>) metadata.get("checkpointResumeBlockingIssueKinds");
    }

    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> immutableBlockingIssues(Map<String, Object> metadata) {
        return (List<Map<String, Object>>) metadata.get("checkpointResumeBlockingIssues");
    }

    private static List<?> immutableRecommendedActions(Map<String, Object> metadata) {
        return (List<?>) metadata.get("checkpointResumeRecommendedActions");
    }

    private static Map<String, Object> issue(
            String kind,
            String code,
            String severity,
            boolean blocking,
            String artifact,
            String message,
            String action) {
        return Map.of(
                "kind", kind,
                "code", code,
                "severity", severity,
                "blocking", blocking,
                "artifact", artifact,
                "message", message,
                "action", action);
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Integer> immutableIssueCountsByKind(Map<String, Object> metadata) {
        return (Map<String, Integer>) metadata.get("checkpointResumeIssueCountsByKind");
    }

    @SuppressWarnings("unchecked")
    private static Map<String, String> immutableIssueSeveritiesByKind(Map<String, Object> metadata) {
        return (Map<String, String>) metadata.get("checkpointResumeIssueSeveritiesByKind");
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Boolean> immutableIssueBlockingByKind(Map<String, Object> metadata) {
        return (Map<String, Boolean>) metadata.get("checkpointResumeIssueBlockingByKind");
    }

    @SuppressWarnings("unchecked")
    private static Map<String, List<String>> immutableIssueArtifactsByKind(Map<String, Object> metadata) {
        return (Map<String, List<String>>) metadata.get("checkpointResumeIssueArtifactsByKind");
    }

    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> immutableIssues(Map<String, Object> metadata) {
        return (List<Map<String, Object>>) metadata.get("checkpointResumeIssues");
    }
}
