package tech.kayys.tafkir.ml.train;

/**
 * Stable checkpoint resume issue identifiers published in trainer summaries.
 */
enum TrainerCheckpointResumeIssueKind {
    MISSING_ARTIFACT(
            "missing-artifact",
            "checkpoint-resume-artifact-missing",
            TrainerCheckpointResumeIssueSeverity.WARNING,
            "restore the missing artifact or resume without checkpoint state",
            "checkpoint artifact is missing on resume"),
    COMPATIBILITY_MISMATCH(
            "compatibility-mismatch",
            "checkpoint-resume-compatibility-mismatch",
            TrainerCheckpointResumeIssueSeverity.ERROR,
            "use a checkpoint generated by the same trainer configuration or start a fresh run",
            null),
    MANIFEST_ENTRY_MISSING(
            "manifest-entry-missing",
            "checkpoint-resume-manifest-entry-missing",
            TrainerCheckpointResumeIssueSeverity.WARNING,
            "restore a complete checkpoint manifest or regenerate the checkpoint set",
            "checkpoint is missing from checkpoint manifest");

    private final String kind;
    private final String code;
    private final TrainerCheckpointResumeIssueSeverity severity;
    private final String action;
    private final String artifactMessageSuffix;

    TrainerCheckpointResumeIssueKind(
            String kind,
            String code,
            TrainerCheckpointResumeIssueSeverity severity,
            String action,
            String artifactMessageSuffix) {
        this.kind = kind;
        this.code = code;
        this.severity = severity;
        this.action = action;
        this.artifactMessageSuffix = artifactMessageSuffix;
    }

    String kind() {
        return kind;
    }

    String code() {
        return code;
    }

    String severity() {
        return severity.value();
    }

    boolean blocking() {
        return severity.blocking();
    }

    String action() {
        return action;
    }

    String artifactMessage(String artifact) {
        if (artifactMessageSuffix == null) {
            return artifact;
        }
        if (artifact == null || artifact.isBlank()) {
            return artifactMessageSuffix;
        }
        return artifact.trim() + ' ' + artifactMessageSuffix;
    }
}
